# Generated by Django 4.0.2 on 2022-03-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
